app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => ['web']], function () {
	Route::get('/', 'GuestController@index');
	Route::get('/about', 'GuestController@about');

	Route::get('shares', 'AccountController@listings');
	Route::get('shares/post/create', 'AccountController@post_listing');
	Route::get('shares/post', 'AccountController@create_listing');
	Route::get('shares/remove', 'AccountController@remove_listing');
	Route::get('shares/reports', 'AccountController@report_listings');

	Route::post('accounts/assign_user', 'AccountController@assign_user');
	Route::post('accounts/assign_slot', 'AccountController@assign_slot');
	Route::get('accounts/{id}/assign', 'AccountController@assign');
	Route::get('accounts/inactives', 'ReportController@inactives');
	Route::get('accounts/{id}/accept', 'AccountController@accept');
	Route::get('accounts/{id}/clear_payment', 'AccountController@clear_payment');
	Route::get('accounts/{id}/clear_account', 'AccountController@clear_account');
	Route::resource('accounts', 'AccountController');

	Route::get('groups.json', 'GroupController@json');
	Route::resource('groups', 'GroupController');

	Route::resource('memberships', 'MembershipSlotController');

	Route::get('review/{id}', 'ComplaintController@create');
	Route::resource('complaints', 'ComplaintController');
	
	Route::get('users.json', 'UserController@json');
	Route::post('users/update', 'UserController@update_user');
	Route::resource('users', 'UserController');

	Route::get('events.json', 'EventController@json');
	Route::get('events/mine/{id}', 'EventController@my_events');
	Route::resource('events', 'EventController');

	Route::post('/resources/renting', 'ResourceController@store_rent');
	Route::get('/resources/rent', 'ResourceController@rent');
	Route::get('/resources/unpaid_rent', 'ResourceController@unpaid_listing');
	Route::get('/resources/{id}/paid', 'ResourceController@paid_listing');
	Route::get('/resources/mylistings', 'ResourceController@my_listings');
	Route::get('/resources/golf', 'ResourceController@golf');
	Route::get('/resources/maintenance', 'ResourceController@maintenance');

	
	


	Route::group(['prefix' => 'config'], function ()
	{
		Route::get('resource_types.json', 'ResourceController@type_json');
		Route::get('resources_golf.json', 'ResourceController@golf_json');
		Route::get('resources.json', 'ResourceController@json');
		Route::resource('resources', 'ResourceController');

		Route::get('slots.json', 'MembershipSlotController@json');
		Route::post('slots/update', 'MembershipSlotController@update_slot');
		Route::resource('membership_slots', 'MembershipSlotController');
	});

	// ---- REPORTS ---- 

	Route::get('graph_options.json', 'ReportController@graph_options');
	Route::group(['prefix' => 'reports'], function () {
    	Route::get('newusers', 'ReportController@newusers');
    	Route::post('newusers', 'ReportController@newusers');
    	Route::get('newusers.tsv/{start}/{end}/{graph_interval}', 'ReportController@newusers_data');

    	Route::get('inactive_members', 'ReportController@inactives');

    	Route::get('user_activity_of_group', 'ReportController@user_activity_of_group');
    	Route::post('user_activity_of_group', 'ReportController@user_activity_of_group');
    	Route::get('user_activity_of_group.tsv/{start}/{end}/{group_id}', 'ReportController@user_activity_of_group_data');

    	Route::get('club_share_transfers', 'ReportController@club_share_transfers');

    	Route::get('facility_usage', 'ReportController@facility_usage');
    	Route::post('facility_usage', 'ReportController@facility_usage');
    	Route::get('facility_usage.tsv/{start}/{end}/{facility_type}', 'ReportController@facility_usage_data');
    	Route::get('facility_usage.tsv/{start}/{end}', 'ReportController@facility_usage_data');

    	Route::get('user_activity_within_event', 'ReportController@user_activity_within_event');
    	Route::post('user_activity_within_event', 'ReportController@user_activity_within_event');
    	Route::get('user_activity_within_event.tsv/{start}/{end}/{graph_interval}/{facility_type}', 'ReportController@user_activity_within_event_data');
	});

	// Authentication routes...
	Route::get('auth/login', 'Auth\AuthController@getLogin');
	Route::post('auth/login', 'Auth\AuthController@postLogin');
	Route::get('auth/logout', 'Auth\AuthController@getLogout');

	// Registration routes...
	Route::get('auth/register', 'Auth\AuthController@getRegister');
	Route::post('auth/register', 'Auth\AuthController@postRegister');

});



/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Zizaco\Entrust\Traits\EntrustUserTrait;

use App\UserAccountRelation;

class User extends Authenticatable
{
    use SoftDeletes;
    use EntrustUserTrait;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function account(){
        return $this->belongsTo('App\Account');
    }

    public function complaints(){
        return $this->hasMany('App\Complaint');
    }

    /**
     * Get the resources this user has rented.
     */
    public function rent_listing()
    {
        return $this->hasMany('App\RentResource', 'rent_resources', 'id', 'id');
    }

    public function is_owner(){
        $account = $this->account;
        if ($account){
            $owner = $account->owner();
            if ($owner)
                return $owner->id == $this->id;
        }

        return FALSE;
    }

    public function getDisplayNameAttribute($value)
    {
        $split = explode("(", $this->name);

        if (count($split) > 1){
            $value = $split[0];
        }else{
            $value = $this->name;
        }
        return trim($value);
    }
}

resources/views/about.blade.php
@extends('layouts.master')

@section('title', 'About Us')

@section('content')

<div class="container">
	<div class="jumbotron">
		<h2>An integrated solution</h2>
		<p>The thing about GGMS is that be lorem the ipsum quite effectively in comparison to other foxes and dogs.</p>
	</div>

	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-body">
				<h4>What makes GGMS different?</h4>
				<p>
					Produce some abstract, a short paragraph describing how GGMS is different from other golf course management systems.
				</p>
			</div>
		</div>
	</div>

	
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-body">
				<h4>New member applications</h4>
				@if ($user)
				<p>As concerned members of our beloved community, please review 
						<a href="{{ action('ComplaintController@index') }}">the new applicants</a>
					 who wish to join our golf community.</p>
					 @endif
				<p>The list below shows a few of the new applicants:</p>
				
			</div>
		</div>
	</div>
	

	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-body">
				<h4>On-going events</h4>
				
			</div>
		</div>
	</div>
</div>
@stop

resources/views/accounts.blade.php
@extends('layouts.master')

@section('title', 'User List')

@section('content')
<div class="page-header">
	@if(isset($inactive) && $inactive)
		<h1>
			Inactive Accounts 
			@if ($user->hasRole('membership_manager'))
				<div class="pull-right">
					<a class="btn btn-primary" href="{{action('AccountController@create')}}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
						&nbsp New
					</a>
				</div>
			@endif
		</h1>
	@else
		<h1>
			Membership Accounts 
			@if ($user->hasRole('membership_manager'))
				<div class="pull-right">
					<a class="btn btn-primary" href="{{action('AccountController@create')}}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
						&nbsp New
					</a>
				</div>
			@endif
		</h1>
	@endif

</div>
@if($user->hasRole('membership_manager'))
<div class="container">
	<p>As a membership manager, you can <a href="{{ action('ComplaintController@index') }}">view the list of pending accounts</a> to accept or deny applications for membership.</p>
</div>
@elseif($user->hasRole('marketing_manager'))
<div class="container">
	<p>As a marketing manager, you can <a href="{{ action('ReportController@inactives') }}">view the list of inactive accounts</a> to follow up payment from account owners.</p>
</div>
@endif
<div class="table-responsive">
	<table class="table table-striped">
		<tr>
			<th class="col-md-2">Membership holder</th>
			<th class="col-md-2">Status</th>
			<th class="col-md-2">Membership type</th>
			<th class="col-md-3">Options</th>
		</tr>
		@foreach($accounts as $account)
		<tr>
			<td class="col-md-2">
				@if ($account->owner())
					{{ $account->owner()->display_name }}
				@else
					No owner
				@endif
			</td>
			<td class="col-md-2">
				{{ $account->status }}
				@if ($user && $user->hasRole('finance_manager') && $account->remarks != NULL && $account->status == 'Inactive')
				<BR />
				<span class="label label-warning">{{ str_limit($account->remarks, 25, '...') }}</span>
				@endif
			</td>
			<td class="col-md-2">
				@if (null !== $account->current_membership_slot())
					<?php print_r($account->current_membership_slot()['type']); ?>
				@else
					No membership yet
				@endif
			</td>
			<td class="col-md-3">
				<div class="btn-group" role="group" aria-label="Options">
					<a class="btn btn-sm btn-default" href="{{action('AccountController@show', ['id' => $account->id])}}"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span>&nbsp Account</a>
					@if ($account->owner())
						<a class="btn btn-sm btn-default" href="{{action('UserController@show', ['id' => $account->owner()->id])}}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp Owner</a>
					@endif
					
				</div>
				
				@if ($user && $user->hasRole('membership_manager'))

				@if ($account->status == 'Paid')
				&nbsp
				<a class="btn btn-sm btn-default" href="{{action('AccountController@clear_account', ['id' => $account->id])}}"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp Accept</a>

				@endif

				@endif

				
			</td>
		</tr>
		@endforeach
	</table>
</div>


@stop

resources/views/complaints.blade.php
@extends('layouts.master')

@section('title', 'Pending Accounts')

@section('content')
<div class="page-header">
	<h1>Pending accounts</h1>
	<p class="help-block">As existing members of this golf club, you are encouraged to participate in the review phase of the application process.
    Please let us know if there are any complaints on new membership applications.</p>
</div>
@if (count($accounts) == 0)
<p>There are currently no pending accounts.</p>
@else
<div class="table-responsive">
	<table class="table table-striped">
		<tr>
			<th class="col-md-6">Membership holder</th>
			<th class="col-md-2 hidden-xs">Complaints</th>
			<th class="col-md-4">Options</th>
		</tr>
		@foreach($accounts as $account)
		<tr>
			<td class="col-md-6">
				@if ($account->owner())
				<a href="{{action('AccountController@show', ['id' => $account->id])}}">
					{{ $account->owner()->display_name }}
				</a>
				@else
					No owner
				@endif
			</td>
			<td class="col-md-2 hidden-xs">
				{{ App\Complaint::where('account_id', '=', $account->id)->count() }}
			</td>
			<td class="col-md-4">
				<div class="btn-group" role="group" aria-label="Options">
					<a class="btn btn-sm btn-default" href="{{action('AccountController@show', ['id' => $account->id])}}"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span>&nbsp Account</a>
					@if ($account->owner())
						<a class="btn btn-sm btn-default" href="{{action('UserController@show', ['id' => $account->owner()->id])}}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp Owner</a>
					@endif
					@if ($user->hasRole('user') && $user->is_owner())
					<a class="btn btn-sm btn-default" href="{{url('review', ['id' => $account->id])}}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp Review</a>
					@endif
				
				</div>
				@if ($user && $user->hasRole('membership_manager'))
				<div class="btn-group" role="group" aria-label="Options">
					&nbsp
					<a class="btn btn-sm btn-primary" href="{{action('AccountController@accept', ['id' => $account->id])}}"> <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp Accept</a>
					&nbsp
					<a class="btn btn-sm btn-danger" href="{{action('AccountController@destroy', ['id' => $account->id])}}"> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>&nbsp Deny</a>
				</div>
				@endif
			</td>
		</tr>
		@endforeach
	</table>
</div>
@endif
@stop

resources/views/events.blade.php
@extends('layouts.master')

@section('title', 'Event List')

@section('content')
<div class="page-header">
	<h1>
		Event list
		@if ($user->hasRole('marketing_manager'))
			<div class="pull-right">
				<a class="btn btn-primary" href="{{action('EventController@create')}}">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
					&nbsp New
				</a>
			</div>
		@endif
	</h1>
</div>
<div class="table-responsive">
	<table class="table table-striped">
		<tr>
			<th class="col-md-3">Name of event</th>
			<th class="col-md-5">Description</th>
			<th class="col-md-2">Date of event</th>
			<th class="col-md-2">Date creation (event)</th>
		</tr>
		@foreach($events as $event)
		<tr>
			<td class="col-md-3">
				<a href="{{action('EventController@show', ['id' => $event->id])}}">
					{{ $event->name }}
				</a>
			</td>
			<td class="col-md-5">{{ $event->description }}</td>
			<td class="col-md-2">{!! display_precise_date($event->start_date) !!}</td>
			<td class="col-md-2">{!! display_precise_date($event->created_at) !!}</td>
		</tr>
		@endforeach
	</table>
</div>
@stop

resources/views/groups.blade.php
@extends('layouts.master')

@section('title', 'Group List')

@section('content')
<div class="page-header">
	<h1>
		Groups
		@if ($user->hasRole('membership_manager'))
			<div class="pull-right">
				<a class="btn btn-primary" href="{{action('GroupController@create')}}">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
					&nbsp New
				</a>
			</div>
		@endif
		
	</h1>
</div>
<?php $i = 0; ?>
@foreach ($categories as $category)
<?php $i = $i %= 3; if ($i == 0): ?>
<div class="row">
<?php endif; ?>
<div class="col-md-4">
	<div class="panel panel-default">
		<div class="panel-heading">{{ ucwords($category->type) }}</div>
		<div class="panel-body">
			<?PHP $groups = $category->groups; ?>

			@foreach($groups as $group)
			<div class="group">
				<a href="{{ action('GroupController@show', ['id' => $group->id]) }}">
					{{ $group->name }}
				</a>
				<!--
				<a class="btn btn-sm btn-default" href="{{action('GroupController@edit', ['id' => $group->id])}}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp Edit</a>
				&nbsp
				<a class="btn btn-sm btn-danger" href="{{action('GroupController@destroy', ['id' => $group->id])}}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span>&nbsp Delete</a>
			-->
			</div>
			@endforeach

		</div>
	</div>
</div>
<?php if ($i == 0): ?>
</div>
<?php endif; $i++; ?>
@endforeach

@stop

resources/views/home.blade.php
@extends('layouts.master')

@section('title', 'Home page')

@section('content')

<div class="container">
	<div class="jumbotron">
		<h2>Generic Golf Management System</h2>
		@if ($user)
			<p>Hi {{ trim($user->display_name) }}, welcome back!</p>
		@else
			<p>Welcome!</p>
		@endif
		<p><a class="btn btn-primary btn-lg" href="{{ action('GuestController@about') }}" role="button">Learn more</a></p>
	</div>

	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-body">
				<h4>What makes GGMS different?</h4>
				<p>
					Produce some abstract, a short paragraph describing how GGMS is different from other golf course management systems.
				</p>
			</div>
		</div>
	</div>

	
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-body">
				<h4>New member applications</h4>
				@if ($user)
				<p>As concerned members of our beloved community, please review 
						<a href="{{ action('ComplaintController@index') }}">the new applicants</a>
					 who wish to join our golf community.</p>
					 @endif
				<p>The list below shows a few of the new applicants:</p>
				<UL>
					@foreach ($pending_accounts as $pending_account)
						@if ($pending_account->owner())
							<LI>{{ $pending_account->owner()->display_name }}</LI>
						@endif
					@endforeach
				</UL>
			</div>
		</div>
	</div>
	

	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-body">
				<h4>On-going events</h4>
				@if (count($events) > 0)
					<ul>
						@foreach ($events as $event)
							<li>{{ $event->name }}</li>
						@endforeach
					</ul>
				@else
					<p>No events today. <a href="{{ action('EventController@index') }}">Click here</a> to see more upcoming events.</p>
				@endif
			</div>
		</div>
	</div>
</div>
@stop

resources/views/resources.blade.php
@extends('layouts.master')

@section('title', 'Facilities List')

@section('content')
<div class="page-header">
	<h1>
		Facilities
		<div class="pull-right">
			<a class="btn btn-default" href="{{action('ResourceController@rent')}}">
				<span class="glyphicon glyphicon-paste" aria-hidden="true"></span>
				&nbsp Rent a facility
			</a>
		@if ($user->hasRole('system_administrator'))
			
				<a class="btn btn-primary" href="{{action('ResourceController@create')}}">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
					&nbsp New
				</a>
		@endif
		</div>
	</h1>
</div>
<div class="content">
	<h2>View facilities</h2>
	<p class="help-block">These are the list of facilities that can be rented by members of the golf community.</p>
	<div class="table-responsive">
		<table class="table table-striped">
			<tr>
				<th class="col-md-12">Name of Facility</th>
			</tr>
			@foreach($resources as $resource)
			<tr>
				<td class="col-md-12">
					<a href="{{action('ResourceController@show', ['id' => $resource->id])}}">
						{{ $resource->name }}
					</a>
				</td>
			</tr>
			@endforeach
		</table>
	</div>
</div>
<hr>
<div class="content">
	<h2>Rentals today</h2>
	@if (count($listings) == 0)
		<p>There are no facilities being rented today.</p>
	@else
	<p class="help-block">These are the facilities being rented today.</p>
	<div class="table-responsive">
		<table class="table table-striped">
			<tr>
				<th class="col-md-3">Name of Facility and Renter</th>
				<th class="col-md-1">Status</th>
				<th class="col-md-1">Rental start time</th>
				<th class="col-md-1">Rental end time</th>
			</tr>
			
			@foreach($listings as $listing)
			<tr>
				<td class="col-md-3">
					<a href="{{action('ResourceController@show', ['id' => $listing->resource->id])}}">
						{{ $listing->resource->name}}
					</a>
					 by
					 <a href="{{action('UserController@show', ['id' => $listing->user->id])}}">
					 	{{ $listing->user->display_name }}
					</a>
				</td>
				<td class="col-md-1">{{ $listing->status }}</td>
				<td class="col-md-1">{{ Carbon\Carbon::parse($listing->start_time)->format('h:i A') }}</td>
				<td class="col-md-1">
					{{ Carbon\Carbon::parse($listing->end_time)->format('h:i A') }}
				</td>
			</tr>
			@endforeach
		</table>
	</div>
	@endif
</div>
@stop

resources/views/slots.blade.php
@extends('layouts.master')

@section('title', 'Membership Slots')

@section('content')
<div class="page-header">
	<h1
		>Membership Slots
		<div class="pull-right">
			<a class="btn btn-primary" href="{{action('MembershipSlotController@create')}}">
				<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
				&nbsp New
			</a>
		</div>
	</h1>
</div>
<div class="table-responsive">
	<table class="table table-striped">
		<tr>
			<th class="col-md-1">Slot ID</th>
			<th class="col-md-2">Slot type</th>
			<th class="col-md-3">Slot description</th>
			<th class="col-md-2">Owned by</th>
		</tr>
		@foreach($slots as $slot)
		<tr>
			<td class="col-md-1">
					{{ $slot->id }}
			</td>
			<td class="col-md-2">
				<a href="{{ action('MembershipSlotController@show', ['id' => $slot->id]) }}">
					{{ $slot->type }}
				</a>
			</td>
			<td class="col-md-3">
				{{ $slot->description }}
			</td>
			<td class="col-md-2">
				@if ($slot->account() && $slot->account()->owner())
				    {{ $slot->account()->owner()->display_name }}
			    @else
			      	-
			    @endif
			</td>
			</tr>
			@endforeach
		</table>
	</div>
	@stop

resources/views/users.blade.php
@extends('layouts.master')

@section('title', 'User List')

@section('content')
<div class="page-header">
	<h1>
		Members
		@if ($user->hasRole('membership_manager'))
			<div class="pull-right">
				<a class="btn btn-primary" href="{{action('UserController@create')}}">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
					&nbsp New
				</a>
			</div>
		@endif
	</h1>
</div>
<div class="table-responsive">
	<table class="table table-striped">
		<tr>
			<th class="col-md-4">Name of member</th>
			<th class="col-md-4">Membership holder</th>
		</tr>
		@foreach($users as $user)
		<tr>
			<td class="col-md-4">
				<a href="{{ action('UserController@show', ['id' => $user->id]) }}">
					{{ $user->display_name }}
				</a>
			</td>
			<td class="col-md-4">
				@if ($user->account == FALSE)
					No access
				@elseif ($user->account_type != 'owner')
					@if ($user->account->owner())
					<a href="{{ action('UserController@show', ['id' => $user->account->owner()->id]) }}">
						<?PHP echo $user->account->owner()->display_name ?>
					</a>
					@else
						No owner
					@endif
				@else
					Myself
				@endif
				</td>
			</tr>
			@endforeach
		</table>
	</div>
	@stop